### ISSUE TITLE
noSuchInstance

### ISSUE THREAD

**Issue by jmgorro** [johan/munin#1]
Hello.
I'm using this perl script to monitor NetApp disk usage. I've 2 controllers and, on both, OID index 10 fails with: 
Argument "noSuchInstance" isn't numeric in pack at ./snmp_<system_local_name>_netapp_diskusage_10 line 90.
Command on same server: snmpget -c public -v1 <system_local_name> .1.3.6.1.4.1.789.1.5.4.1.2.10
retrieves the volume string name without problems.
Volumes with index greater or lower than 10 are monitorized without problems.

**Comment by johan** [comment]
You want to contact the [Munin project](http://munin-monitoring.org/) itself, not file issues on this unmaintained way-back-in-time git clone of many years ago.
